MySQL
CREATE TABLE posts (
    id INT(6) AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(350) NOT NULL,
    link VARCHAR(350) NOT NULL,
    source_link VARCHAR(350),
    source_name VARCHAR(350),
    description MEDIUMTEXT,
    resource VARCHAR(150) NOT NULL,
    image VARCHAR(300),
    publish_date DATETIME,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

//POSTGRESQL
CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    title VARCHAR(350) NOT NULL,
    link VARCHAR(350) NOT NULL,
    source_link VARCHAR(350),
    source_name VARCHAR(350),
    description TEXT,
    resource VARCHAR(150) NOT NULL,
    image VARCHAR(300),
    publish_date DATE TIME,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

    dates DATE NOT NULL DEFAULT CURRENT_DATE
);
